### ISSUE TITLE
class Person 

### ISSUE THREAD

**Issue by umohm1** [learn-co-curriculum/ruby-music-library-cli#29]
Inside 008_findable_module_spec.rb there's:

class Person
    extend Concerns::Findable
  end

We haven't worked with a Person class  inside this lab.  I think it means Genre according to the lesson.

**Comment by gj** [comment]
Hi @umohm1 !

Using `Person` was actually intentional, as the test was looking to determine whether `extend`ing *any* class with the `Concerns::Findable` module would make the module's methods available to that class. Using an existing class (like `Genre`) would've created some naming conflicts, so `Person` was picked as a neutral party.

That being said, I agree that it's a bit confusing for Person to pop up out of nowhere, and I've reworked that in the updated lab that I'll be pushing out shortly.

Thanks for raising the issue! 🙂
