### ISSUE TITLE
find_or_create_by_name(name)

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/ruby-music-library-cli#31]
having the code to respond to 3 different classes is a mystery to me

**Comment by gj** [comment]
Hi @ICanDoAllThingThroughChrist,

Could you provide some more information? This seems like it might be the kind of query that would be better for the [Ask a Question](http://help.learn.co/ask-a-question/how-to-ask-a-good-question) feature on [Learn.co](https://learn.co/).

If you think this is due to a specific bug or deficiency in the curriculum, would you mind expanding on the idea a bit? I'd be happy to take a look into your concerns. 🙂

**Comment by gj** [comment]
Hi @ICanDoAllThingThroughChrist,

I'm gonna go ahead and close this one for now, but if you have any further information feel free to reopen and highlight me!
