### ISSUE TITLE
Does not recognize not re-coding song#create method in find_or_create_by_name

### ISSUE THREAD

**Issue by ScottMS724** [learn-co-curriculum/ruby-music-library-cli#44]
Stuck on the error that is telling me not to re-code the #create method functionality. Two zoom calls were not able to get it to pass. All methods seem correct but it seems to be an error with the tests themselves.

**Comment by morgvanny** [comment]
Hi Scott, would you mind pasting any related complete error messages here? Also, if you run `learn save` it will push your changes up to your forked repository here, which would allow us to take a deeper look at what's going on.

**Comment by ScottMS724** [comment]
The error message:

"Failures:

  1) Song .find_or_create_by_name invokes .create instead of re-coding the samefunctionality
     Failure/Error: expect(Song).to receive(:create).with("Kaohsiung Christmas")

       (Song (class)).create("Kaohsiung Christmas")
           expected: 1 time with arguments: ("Kaohsiung Christmas")
           received: 0 times
     # ./spec/007_findable_songs_spec.rb:32:in `block (3 levels) in <top (required)>'"

"rspec ./spec/007_findable_songs_spec.rb:31 # Song .find_or_create_by_name invokes .create instead of re-coding the same functionality"

ran learn save

**Comment by morgvanny** [comment]
Ah, so the problem actually lies in your .find_by_name method. The tests beforehand actually aren't comprehensive enough to catch your particular mistake, so you did pass the tests for that method.

Essentially, when you do this:
self.all.detect { |song| song.name = song_name }

You are iterating through all of the songs, and on the very first iteration, you are setting song.name equal to song_name rather than using == to compare if they are the same. It returns a truthy value, basically no matter what, meaning you will return a match even if you shouldn't.

That means later, when .find_or_create_by is called, it never fails to .find_by_name so it never gets to actually create a new song. You can test to confirm this by placing a binding.pry before line 38, running the tests, and do `exit` once, to get to the next test that expects a new song to be created. Then try looking at Song.all, song_name, and try out find_by_name(song_name). You'll see it returns a truthy value when it should not, and therefore will never call create(song_name).

So all you have to do to solve this is change that line to use == instead of just =

Thanks for bringing this up though, because it would be ideal if the tests caught this earlier, when they were checking the .find_by_name method
