### ISSUE TITLE
Song.find_by_name method spec seems broken

### ISSUE THREAD

**Issue by MaxBrooks114** [learn-co-curriculum/ruby-music-library-cli#51]
The spec file seems to want the class returned instead of the song instance itself.  The following code makes the test pass, this is not correct. 

``` def self.find_by_name(name)
   found= all.find do |song| 
     song.name == name
       end
      return found.class
    end

**Comment by lizbur10** [comment]
Hi there! I'm sorry to hear you were having difficulties - apologies for the inconvenience! I'm not sure what was causing the issue but the tests have since been updated and the problem doesn't appear to be happening anymore, so I'm going to go ahead and close this issue. 

Thanks for contributing to the Flatiron School curriculum! 💙
