### ISSUE TITLE
All three videos at the bottom of the README are unavailable

### ISSUE THREAD

**Issue by sopharsogood** [learn-co-curriculum/ruby-music-library-cli#64]
Each says "Video Unavailable — This video is private."

**Comment by ihollander** [comment]
Fixed by https://github.com/learn-co-curriculum/ruby-music-library-cli/commit/54b04b99522f766d8b7ea51fa62ad3c416c4c221

Thanks for flagging this @sopharsogood! These videos were recorded by an instructor who is no longer at Flatiron and were removed from YouTube, so we have removed them from the readme.
